echo off
fasmarm aes_random_stuff.asm
fasmarm arith64.asm
fasmarm array.asm
fasmarm arrayBitManip.asm
fasmarm avx512_random_stuff.asm
fasmarm aw-wav.asm
fasmarm bithacks.asm
fasmarm bmiStuff.asm
fasmarm bmi2Stuff.asm
fasmarm bswap.asm
fasmarm calcPi.asm
fasmarm convert.asm
fasmarm cute_alloc.asm
fasmarm detab.asm
fasmarm findFirstSet.asm
REM fasmarm floatShit.asm sorry but no
fasmarm gcd_Lcm.asm
fasmarm intDiv.asm
fasmarm intSqrt.asm
fasmarm intToBase.asm
fasmarm isLeapYear.asm
fasmarm isPowerOf2.asm
fasmarm isPowerOf4.asm
fasmarm lcmArray.asm
fasmarm mostSignificantIndex.asm
fasmarm mulDiv.asm
fasmarm mulStuff.asm
fasmarm my_ia32intrin.asm
fasmarm my_mm_malloc.asm
fasmarm my_string.asm
fasmarm nextPowerOf2.asm
fasmarm oppositeSigns.asm
fasmarm rand.asm
fasmarm rotate.asm
fasmarm sumTo.asm
pause