nasm -f elf32 arith64.asm
nasm -f elf32 array.asm
nasm -f elf32 bmiStuff.asm
nasm -f elf32 bmi2Stuff.asm
nasm -f elf32 convert.asm
nasm -f elf32 characterFilter.asm
nasm -f elf32 debugBreak.asm
nasm -f elf32 detab.asm
nasm -f elf32 floatShit.asm
nasm -f elf32 gcd_Lcm.asm
nasm -f elf32 intDiv.asm
nasm -f elf32 intSqrt.asm
nasm -f elf32 isLeapYear.asm
nasm -f elf32 isPowerOf2.asm
nasm -f elf32 mulStuff.asm
nasm -f elf32 nextPowOf2.asm
nasm -f elf32 oppositeSigns.asm
nasm -f elf32 rotate.asm
pause